// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCCZVdhmr3IwJYg2anWdA2Fy8RpZlHpG4',
    appId: '1:169805195189:web:a18a59df92a7fab7e71bfc',
    messagingSenderId: '169805195189',
    projectId: 'blue-bird-academy',
    authDomain: 'blue-bird-academy.firebaseapp.com',
    storageBucket: 'blue-bird-academy.firebasestorage.app',
    measurementId: 'G-JCMVCTN1VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKLDCqgbQjJzX28PVyTfqi-8YdwWai7E',
    appId: '1:169805195189:android:f814c5e86a7628a5e71bfc',
    messagingSenderId: '169805195189',
    projectId: 'blue-bird-academy',
    storageBucket: 'blue-bird-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvfZyisbE7OrRlKC1ngRpRpli7cDQFg18',
    appId: '1:169805195189:ios:c1753d78fc8fac6de71bfc',
    messagingSenderId: '169805195189',
    projectId: 'blue-bird-academy',
    storageBucket: 'blue-bird-academy.firebasestorage.app',
    iosBundleId: 'com.example.blueBird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvfZyisbE7OrRlKC1ngRpRpli7cDQFg18',
    appId: '1:169805195189:ios:c1753d78fc8fac6de71bfc',
    messagingSenderId: '169805195189',
    projectId: 'blue-bird-academy',
    storageBucket: 'blue-bird-academy.firebasestorage.app',
    iosBundleId: 'com.example.blueBird',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCCZVdhmr3IwJYg2anWdA2Fy8RpZlHpG4',
    appId: '1:169805195189:web:31fd9777200f9dd8e71bfc',
    messagingSenderId: '169805195189',
    projectId: 'blue-bird-academy',
    authDomain: 'blue-bird-academy.firebaseapp.com',
    storageBucket: 'blue-bird-academy.firebasestorage.app',
    measurementId: 'G-DK3XNLF5JT',
  );
}
